[tasks.install-llvm-tools]

[tasks.flip-link]

[tasks.objcopy-central]
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "rmk-central.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral]
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral",
    "--",
    "-O",
    "ihex",
    "rmk-peripheral.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.uf2-central]
command = "python"
args = [
    "../scripts/uf2conv.py",
    "rmk-central.hex",
    "-c",
    "-f",
    "0xADA52840",                  # Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "rmk-central.uf2",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral]
command = "python"
args = [
    "../scripts/uf2conv.py",
    "rmk-peripheral.hex",
    "-c",
    "-f",
    "0xADA52840",                  # Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "rmk-peripheral.uf2",
]
dependencies = ["objcopy-peripheral"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral"]
