[tasks.install-llvm-tools]
# install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
# install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.objcopy-central]
# install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
#     "objcopy",
#     "--help",
# ] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "rmk-central.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral-left]
# install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
#     "objcopy",
#     "--help",
# ] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral_left",
    "--",
    "-O",
    "ihex",
    "rmk-peripheral-left.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral-right]
# install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
#     "objcopy",
#     "--help",
# ] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral_right",
    "--",
    "-O",
    "ihex",
    "rmk-peripheral-right.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.uf2-central]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-central.hex",
    "--output-path",
    "rmk-central.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral-left]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-peripheral-left.hex",
    "--output-path",
    "rmk-peripheral-left.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-peripheral-left"]

[tasks.uf2-peripheral-right]
install_crate = { crate_name = "cargo-hex-to-uf2", binary = "cargo", test_arg = [
    "hex-to-uf2",
    "--help",
] }
command = "cargo"
args = [
    "hex-to-uf2",
    "--input-path",
    "rmk-peripheral-right.hex",
    "--output-path",
    "rmk-peripheral-right.uf2",
    "--family",
    "nrf52840",
]
dependencies = ["objcopy-peripheral-right"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral-left", "uf2-peripheral-right"]
