pub(crate) const COL: usize = 10;
pub(crate) const ROW: usize = 4;
pub(crate) const NUM_LAYER: usize = 8;
pub(crate) const NUM_ENCODER: usize = 0;
#[rustfmt::skip]
pub const fn get_default_keymap() -> [[[::rmk::action::KeyAction; COL]; ROW]; NUM_LAYER] {
    [
        [
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Grave),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Comma),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Dot),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::P),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Y),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::L),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::R),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::C),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::G),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F),
                ),
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::A),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::O),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::E),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::U),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::I),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::S),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::N),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::T),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::H),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::D),
                ),
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Slash),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Q),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::J),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::K),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::X),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Z),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::V),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::W),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::M),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::B),
                ),
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LShift),
                ),
                ::rmk::action::KeyAction::Single(::rmk::action::Action::LayerOn(1u8)),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Space),
                ),
                ::rmk::action::KeyAction::Single(::rmk::action::Action::LayerOn(2u8)),
            ],
        ],
        [
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::BrightnessDown),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::BrightnessUp),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Tab),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::AudioVolDown),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::AudioVolUp),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Delete),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Enter),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Up),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::End),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Home),
                ),
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LShift),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LCtrl),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LAlt),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LGui),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::AudioMute),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Backspace),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Right),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Down),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Left),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::PageUp),
                ),
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::PrintScreen),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Z),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::X),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::C),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::V),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::PageDown),
                ),
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::LayerToggle(6u8),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(::rmk::action::Action::LayerOn(5u8)),
                ::rmk::action::KeyAction::Single(::rmk::action::Action::LayerOn(2u8)),
            ],
        ],
        [
            [
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc2),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::RightBracket),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::RightBracket),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc9),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc4),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Dot),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::NonusHash),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::NonusHash),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc0),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Comma),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Escape),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc8),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Minus),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::KpEqual),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Equal),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::RShift),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::RCtrl),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LAlt),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LGui),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc7),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
            ],
            [
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::NonusBackslash),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc3),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Minus),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc1),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc5),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Quote),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::WithModifier(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::International1),
                    ::rmk::keycode::ModifierCombination::new_from(
                        false,
                        false,
                        false,
                        true,
                        false,
                    ),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Quote),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::International1),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::NonusBackslash),
                ),
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(::rmk::action::Action::LayerOn(4u8)),
                ::rmk::action::KeyAction::Single(::rmk::action::Action::LayerOn(1u8)),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LeftBracket),
                ),
                ::rmk::action::KeyAction::Transparent,
            ],
        ],
        [
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc1),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc2),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc3),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc4),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc5),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc0),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc9),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc8),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc7),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc6),
                ),
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LShift),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LCtrl),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LAlt),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LGui),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F11),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::RShift),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::RCtrl),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LAlt),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LGui),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F12),
                ),
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F1),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F2),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F3),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F4),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F5),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F10),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F9),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F8),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F7),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F6),
                ),
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
        ],
        [
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Semicolon),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Macro0),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Macro1),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Macro2),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Macro3),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Macro4),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
        ],
        [
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseBtn2),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseUp),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseBtn1),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseWheelUp),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::User11),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::User10),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseLeft),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseDown),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseRight),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::MouseWheelDown),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::User4),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::User3),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::User2),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::User1),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::User0),
                ),
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
        ],
        [
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Tab),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Q),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::W),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::E),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::R),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Up),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LShift),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::A),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::S),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::D),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::F),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Right),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Down),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Left),
                ),
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::LCtrl),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Z),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::X),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::C),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::V),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Space),
                ),
                ::rmk::action::KeyAction::Single(::rmk::action::Action::LayerOn(7u8)),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Space),
                ),
                ::rmk::action::KeyAction::Transparent,
            ],
        ],
        [
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc5),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc4),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc1),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc2),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Escape),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Kc3),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Enter),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Grave),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::B),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::T),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::P),
                ),
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::Key(::rmk::keycode::KeyCode::Y),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
            [
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Single(
                    ::rmk::action::Action::LayerToggle(6u8),
                ),
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
                ::rmk::action::KeyAction::Transparent,
            ],
        ],
    ]
}
pub const fn get_default_encoder_map() -> [[::rmk::action::EncoderAction; NUM_ENCODER]; NUM_LAYER] {
    [[], [], [], [], [], [], [], []]
}
