[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip PY32F072xB"

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
KEYBOARD_TOML_PATH =  { value = "keyboard.toml", relative = true }